# Nba Regular Season 2018-19 Data Challenge

Your task will be to take the dataset given, and create an analysis answering the following 10 questions. This project will again test your knowledge of pandas in order to find the answers needed given the data you are presented with.

<!-- PREPARING DATA FOR ANALYSIS-->

In [1]:
# imports
import pandas as pd
#loading and reading data
nba_stats = pd.read_csv('../Pandas Project II/nbastats2018-2019.csv')
nba_stats.head(10)

,Name,Height,Weight,Team,Age,Salary,Points,Blocks,Steals,Assists,...,MP,G,PER,OWS,DWS,WS,WS48,USG,BPM,VORP
0,Alex Abrines,78,200,Oklahoma City Thunder,25,5455236,5.3,0.2,0.5,0.6,...,19.0,31,6.3,0.1,0.6,0.6,0.053,12.2,-3.4,-0.2
1,Quincy Acy,79,240,Phoenix Suns,28,213949,1.7,0.4,0.1,0.8,...,12.3,10,2.9,-0.1,0.0,-0.1,-0.022,9.2,-5.9,-0.1
2,Jaylen Adams,74,190,Atlanta Hawks,22,236854,3.2,0.1,0.4,1.9,...,12.6,34,7.6,-0.1,0.2,0.1,0.011,13.5,-4.4,-0.3
3,Steven Adams,84,265,Oklahoma City Thunder,25,24157304,13.9,1.0,1.5,1.6,...,33.4,80,18.5,5.1,4.0,9.1,0.163,16.4,2.7,3.2
4,Bam Adebayo,82,255,Miami Heat,21,2955840,8.9,0.8,0.9,2.2,...,23.3,82,17.9,3.4,3.4,6.8,0.171,15.8,3.0,2.4
5,Deng Adel,79,200,NaN,21,-,1.7,0.2,0.1,0.3,...,10.2,19,2.7,-0.2,0.0,-0.2,-0.054,9.9,-7.3,-0.3
6,LaMarcus Aldridge,83,260,San Antonio Spurs,33,22347015,21.3,1.3,0.5,2.4,...,33.2,81,22.9,6.4,2.9,9.3,0.167,26.9,1.6,2.5
7,Rawle Alkins,77,225,NaN,21,-,3.7,0.0,0.1,1.3,...,12.0,10,8.1,-0.1,0.0,-0.1,-0.042,19.0,-6.5,-0.1
8,Grayson Allen,77,198,Utah Jazz,23,2074320,5.6,0.2,0.2,0.7,...,10.9,38,7.5,-0.4,0.4,0.0,0.002,24.4,-6.8,-0.5
9,Jarrett Allen,83,237,Brooklyn Nets,20,2034120,10.9,1.5,0.5,1.4,...,26.2,80,18.5,4.4,3.3,7.6,0.175,15.9,2.5,2.4

In [2]:
# print keys to get a fair idea of what my data contains
print(nba_stats.keys())

Index(['Name', 'Height', 'Weight', 'Team', 'Age', 'Salary', 'Points', 'Blocks',
       'Steals', 'Assists', 'Rebounds', 'FT%', 'FTA', 'FG3%', 'FG3A', 'FG%',
       'FGA', 'MP', 'G', 'PER', 'OWS', 'DWS', 'WS', 'WS48', 'USG', 'BPM',
       'VORP'],
      dtype='object')

In [3]:
# drop duplicates before starting? 
nba_stats_ready = nba_stats.drop_duplicates(subset = 'Name').reset_index(drop=True)
nba_stats_ready

,Name,Height,Weight,Team,Age,Salary,Points,Blocks,Steals,Assists,...,MP,G,PER,OWS,DWS,WS,WS48,USG,BPM,VORP
0,Alex Abrines,78,200,Oklahoma City Thunder,25,5455236,5.3,0.2,0.5,0.6,...,19.0,31,6.3,0.1,0.6,0.6,0.053,12.2,-3.4,-0.2
1,Quincy Acy,79,240,Phoenix Suns,28,213949,1.7,0.4,0.1,0.8,...,12.3,10,2.9,-0.1,0.0,-0.1,-0.022,9.2,-5.9,-0.1
2,Jaylen Adams,74,190,Atlanta Hawks,22,236854,3.2,0.1,0.4,1.9,...,12.6,34,7.6,-0.1,0.2,0.1,0.011,13.5,-4.4,-0.3
3,Steven Adams,84,265,Oklahoma City Thunder,25,24157304,13.9,1.0,1.5,1.6,...,33.4,80,18.5,5.1,4.0,9.1,0.163,16.4,2.7,3.2
4,Bam Adebayo,82,255,Miami Heat,21,2955840,8.9,0.8,0.9,2.2,...,23.3,82,17.9,3.4,3.4,6.8,0.171,15.8,3.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,Trae Young,74,180,Atlanta Hawks,20,5356440,19.1,0.2,0.9,8.1,...,30.9,81,17.0,2.5,0.7,3.3,0.062,28.4,-1.1,0.6
517,Cody Zeller,84,240,Charlotte Hornets,26,13528090,10.1,0.8,0.8,2.1,...,25.4,49,17.2,2.6,1.2,3.9,0.150,16.3,2.0,1.2
518,Tyler Zeller,84,253,Atlanta Hawks,29,106974,7.7,0.5,0.2,0.7,...,15.5,6,17.3,0.2,0.1,0.3,0.167,20.1,-2.2,0.0
519,Ante Zizic,83,254,Cleveland Cavaliers,22,1952760,7.8,0.4,0.2,0.9,...,18.3,59,16.2,1.7,0.3,2.0,0.087,18.2,-3.1,-0.3
520,Ivica Zubac,85,240,Los Angeles Clippers,21,1544951,8.9,0.9,0.2,1.1,...,17.6,59,18.9,1.9,1.3,3.2,0.148,20.3,-0.3,0.5

In [30]:
# using nba_stats_ready
# are there any missing values?finding missing values
nan_nba_stats = nba_stats_ready[nba_stats_ready.isnull().any(axis=1)]
nan_nba_stats
# replace all NaN with N/A for clarity sake
nba_stats = nan_nba_stats.fillna('N/A') #df returned to original name nba_stats
nba_stats['FG3%'] = nan_nba_stats['FG3%'].fillna(0)
# nba_stats['FG3%']
nba_stats
# READY TO BE ANALYZED

,Name,Height,Weight,Team,Age,Salary,Points,Blocks,Steals,Assists,...,MP,G,PER,OWS,DWS,WS,WS48,USG,BPM,VORP
5,Deng Adel,79,200,N/A,21,-,1.7,0.2,0.1,0.3,...,10.2,19,2.7,-0.2,0.0,-0.2,-0.054,9.9,-7.3,-0.3
7,Rawle Alkins,77,225,N/A,21,-,3.7,0.0,0.1,1.3,...,12.0,10,8.1,-0.1,0.0,-0.1,-0.042,19.0,-6.5,-0.1
10,Kadeem Allen,75,192,N/A,26,-,9.9,0.2,0.8,4.0,...,21.9,19,16.2,0.7,0.2,1.0,0.111,19.6,-1.1,0.1
14,Ike Anigbogu,82,250,Indiana Pacers,20,1378242,0.0,0.3,0.0,0.3,...,2.0,3,-6.0,-0.1,0.0,-0.1,-0.480,29.1,-14.0,0.0
16,Kostas Antetokounmpo,82,200,N/A,21,-,1.0,0.0,1.0,0.0,...,5.5,2,-0.9,-0.1,0.0,-0.1,-0.247,22.5,-13.3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,Johnathan Williams,81,228,N/A,23,-,6.5,0.3,0.3,0.5,...,15.5,24,15.1,0.7,0.3,1.0,0.135,16.4,-1.7,0.0
507,Robert Williams,82,240,Boston Celtics,21,1654440,2.5,1.3,0.3,0.2,...,8.8,32,18.8,0.5,0.6,1.2,0.201,10.3,4.4,0.5
514,Nick Young,79,210,Denver Nuggets,33,311070,2.3,0.3,0.0,0.5,...,9.3,4,2.3,0.0,0.0,0.0,-0.021,12.7,-7.0,0.0
519,Ante Zizic,83,254,Cleveland Cavaliers,22,1952760,7.8,0.4,0.2,0.9,...,18.3,59,16.2,1.7,0.3,2.0,0.087,18.2,-3.1,-0.3
520,Ivica Zubac,85,240,Los Angeles Clippers,21,1544951,8.9,0.9,0.2,1.1,...,17.6,59,18.9,1.9,1.3,3.2,0.148,20.3,-0.3,0.5

# What was the average age of player in the league?

In [32]:
# using nba_stats
# age? group by age... find mean
# can find mean without groupby? 
#using groupby will result in getting age for each group instead of entire league?
#Pseudo: average_age = nba_stats..index age.mean()
mean_age = nba_stats['Age'].mean()
mean_age 
# result is float of more than two decimal places... round?
mean_age = mean_age.round()

print(f'The average age of player in the entire league is {mean_age}')

The average age of player in the entire league is 25.0

# What player scored the most points?

In [33]:
# finding the top scorer in the league
# first, find the maximum number of points in league,
maximum_points = nba_stats['Points'].max()
# Use filter to get only the players with the most points
# top_scorers = check if data in nba_stats (points) == max points... put data here
top_scorers = nba_stats[nba_stats['Points'] == maximum_points]
# top_scorers
# get the name of the top scorer
top_scorer_name = top_scorers['Name'].tolist() #tolist will bring out the player name only..no index

top_scorer_point = top_scorers['Points'].tolist()
print(f'The player who scored the most points is {top_scorer_name} with {top_scorer_point} points')

The player who scored the most points is ['R.J. Hunter'] with [17.0] points

# What player had the most blocks during the season? Was it a post player (F/C)?

In [34]:
# what is the maximum number of blocks?
maximum_blocks = nba_stats['Blocks'].max()
# maximum_blocks
# Filter nba_stats to get only the player(s) with the most blocks
top_block_players = nba_stats[nba_stats['Blocks'] == maximum_blocks]
# top_block_players
#was it a top scorer?
top_block_player_names = top_block_players['Name']

# Check if the top blocker(s) is a post player (F/C)
#No column with player position data
# Cannot determine this without position data

print(f'The player who had the most blocks during the season is {top_block_player_names}')
print('The nba_stats does not include position data hence it cannot be determined whether the player was F/C')

The player who had the most blocks during the season is 419    Mitchell Robinson
Name: Name, dtype: object
The nba_stats does not include position data hence it cannot be determined whether the player was F/C

# Based on the regular season, who had the best chance to win a title given their win percentage?

In [35]:
# who as it teams? or players?
# if G is the total Games
# and WS is total wins
# then WS/G = win_percentage for each player
# create a new column called win_percentage ->
nba_stats['Win_percentage'] = nba_stats['WS'] / nba_stats['G']
# nba_stats

# Finding the maximum win percentage
max_win_percentage = nba_stats['Win_percentage'].max()

# Filter the DataFrame to include only the team(s)/row with the highest win percentage
best_chance = nba_stats[nba_stats['Win_percentage'] == max_win_percentage]
# best_teams
#Get the name of the team/player with the highest win percentage
best_chance_team = best_chance['Team'].tolist()
best_chance_player = best_chance['Name'].tolist()

print(f'From the data, we can deduce that {best_chance_player} from Team {best_chance_team} had the best chance to win a title')

From the data, we can deduce that ['Rudy Gobert'] from Team ['Utah Jazz'] had the best chance to win a title

In [36]:
# if we are looking for the best team 
# then, maybe.. groupby teams
# aggregate [used to sum by team] ..calc total wins by teams
nba_teams_stats = nba_stats.groupby('Team')
nba_teams_stats = nba_teams_stats.agg({'WS': 'sum', 'G': 'sum'})
# nba_teams_stats 
# calc win percentage for each team
nba_teams_stats['team_win_percent'] = nba_teams_stats['WS'] / nba_teams_stats['G']

# find max win percent
maximum_win_percentage = nba_teams_stats['team_win_percent'].max()

# get team with  highest win percentage
best_team = nba_teams_stats[nba_teams_stats['team_win_percent'] == maximum_win_percentage]
# best_team
# getting team only                            
best_chance_team = best_team.index.tolist()
print(f'From the data, we can deduce that Team {best_chance_team} had the best chance to win a title')

From the data, we can deduce that Team ['Houston Rockets'] had the best chance to win a title

# What player had the best 3-pt percentage?

In [103]:
# finding player with the best 3 point %
# using column 'FG3%'
# maybe just find the max 3pt% ?
# then filter from original data to get rows with data for players in max
# get the names and print line
# nba_stats['FG3%'] = nba_stats['FG3%'].fillna(0) .. already done at the beginning
maximum_3pt = nba_stats['FG3%'].max()
maximum_3pt

maximum_3pt_row = nba_stats[nba_stats['FG3%'] == maximum_3pt]
# maximum_3pt_row
best_3pt_player = maximum_3pt_row['Name'].tolist()
best_3pt_point = maximum_3pt_row['FG3%'].tolist()

print(f'{best_3pt_player} had the best 3-pt percentage with a 3-point percentage of \n{best_3pt_point} ')

['Trevon Duval', 'Eric Moreland', 'Jordan Sibert'] had the best 3-pt percentage with a 3-point percentage of
[1.0, 1.0, 1.0]

# Who played the most minutes during the season

In [43]:
# if MP is minute played.. then find maximum minute played
most_played = nba_stats['MP'].max()

most_played_row = nba_stats[nba_stats['MP'] == most_played]
# most_played_row
most_played_name = most_played_row['Name'].tolist()

print(f'{most_played_name} played the most minutes during the season')

['Clint Capela'] played the most minutes during the season

# What player given their player effiecency rating was the clutchest during the season?

In [47]:
# cluchest player? using PER ...player efficiency ratings
# find max rating
# get row
# get name

highest_per = nba_stats['PER'].max()
cluchest_row = nba_stats[nba_stats['PER'] == highest_per]
cluchest_player  = cluchest_row['Name'].tolist()
cluchest_per = cluchest_row['PER'].tolist()
print(f'Cluchest player will be {cluchest_player} with PER at {cluchest_per}')

Cluchest player will be ['Zhou Qi'] with PER at [80.4]

# What team had the youngest roster?

In [55]:
#using team and ages..groupby
# find mean age per team arrange in ascending order
# index min... print

team_group = nba_stats.groupby('Team')['Age'].mean().sort_values(ascending = True)
team_mean_age = team_group.idxmin()

print(f'The {team_mean_age} had the youngest roster')

The Indiana Pacers had the youngest roster

# Who is the highest paid player during the seasion?

In [86]:
# names... tab with pay(salary)
# subsetting name, team, salary... descending order..

# nba_stats_subset = nba_stats[['Name', 'Team', 'Salary']].reset_index()
# nba_stats_subset_sort = nba_stats_subset.sort_values('Salary', ascending = False)
# nba_stats_subset_sort
# highest = nba_stats_subset.loc[nba_stats_subset['Salary'].idxmax()]
#highest
# ~~~~~~~~~~ 
# Error!.. valueError indice is str must be int /float
# reset column as numeric.. handle N/A 
# fillna as (0)
# using astype to reset Salary column values as integers
# repeat code

nba_stats['Salary'] = pd.to_numeric(nba_stats['Salary'], errors='coerce')
nba_stats['Salary'] = nba_stats['Salary'].fillna(0)
nba_stats['Salary'] = nba_stats['Salary'].astype(int)
nba_stats['Salary']

# repeat code
max_salary = nba_stats['Salary'].max()
highest_row = nba_stats[nba_stats['Salary'] == max_salary]
highest_paid_player = highest_row['Name'].tolist()
highest_salary = highest_row['Salary'].tolist()
print(f'The highest paid player is {highest_paid_player}, with a salary of ${highest_salary}')

The highest paid player is ['Rudy Gobert'], with a salary of $[23241573]

# At the end of a game, who WOULDN'T you want on the Free Throw Line?

In [100]:
# where FT is Free Throw 
# find min ft..
# handle N/A data 
ft_check = nba_stats[nba_stats['FT%'] != 'N/A']
# ft_check['FT%']
minimum_ft = ft_check['FT%'].min()

minimum_ft_row = nba_stats[nba_stats['FT%'] == minimum_ft]

worst_ft_shooter = minimum_ft_row['Name'].tolist()
worst_ft = minimum_ft_row['FT%'].tolist()

print(f"At the end of a game, you wouldn't want {worst_ft_shooter} on the Free Throw Line.\n These players have a Free Throw percentage of {worst_ft} respectively")

At the end of a game, you wouldn't want ['Haywood Highsmith', 'Donatas Motiejunas', 'C.J. Williams'] on the Free Throw Line.
 These players have a Free Throw percentage of [0.0, 0.0, 0.0] respectively